apiVersion: k3d.io/v1alpha3
kind: Simple
name: doctopus
servers: 1
agents: 1
volumes:
  - volume: $MNT_PATH:/mnt/data
    nodeFilters:
      - all
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
options:
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: all
