system: The whole system 

externalSystemOne: External System
externalSystemOne.shape: cloud

externalSystemTwo: External System

externalSystemOne -> System
system -> externalSystemTwo: updates some records