name: Deploy static content to Pages

on:
  push:
    branches: 
      - main
    paths:
      - ".docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: generate docu html
        working-directory: .docs/arc42
        run: |
          bash scripts/export-to-confluence.sh
