name: Deploy static content to confluence page

on:
  push:
    branches: 
      - main
    paths:
      - ".docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: generate and push to confluence
        env:
          ARC42_EXPORT_CONFLUENCE_SPACE_KEY: ${{ secrets.ARC42_EXPORT_CONFLUENCE_SPACE_KEY }}
          ARC42_EXPORT_CONFLUENCE_USER_EMAIL: ${{ secrets.ARC42_EXPORT_CONFLUENCE_USER_EMAIL }}
          ARC42_EXPORT_CONFLUENCE_USER_PAT: ${{ secrets.ARC42_EXPORT_CONFLUENCE_USER_PAT }}
          ARC42_EXPORT_CONFLUENCE_API: ${{ vars.ARC42_EXPORT_CONFLUENCE_API }}         
        working-directory: .docs/arc42
        run: |
          bash scripts/export-to-confluence.sh
