name: Update Backend Image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "backend-${{ github.event_name }}"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "IMAGE_TAG=v${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            IMAGE_TAG="dev-$(git rev-parse --short HEAD)"
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          fi
          echo $IMAGE_TAG
      - name: Build and push image
        run: |
          cd backend
          echo $IMAGE_TAG
          docker build -t ghcr.io/feu-aklos/arc42-sample/backend:$IMAGE_TAG .
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u feu-aklos --password-stdin
          docker push ghcr.io/feu-aklos/arc42-sample/backend:$IMAGE_TAG
