name: Update Backend Image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "backend-${{ github.event_name }}"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            IMAGE_TAG="dev-$(git rev-parse --short HEAD)"
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          fi
          echo $IMAGE_TAG
      - name: Set IMAGE_NAME
        id: set_name
        run: |
          echo "event path: ${{ github.event_path }}"
          cat ${{ github.event_path }}

          if [[ ${{ github.event_path }} == "backend"* ]]; then
            IMAGE_NAME="backend"
          elif [[ ${{ github.event_path }} == "frontend"* ]]; then
            IMAGE_NAME="frontend"
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "image name: $IMAGE_NAME"
      - name: Build and push image
        run: |
          cd $IMAGE_NAME
          echo $IMAGE_TAG
          docker build -t ghcr.io/feu-aklos/arc42-sample/$IMAGE_NAME:$IMAGE_TAG .
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u feu-aklos --password-stdin
          docker push ghcr.io/feu-aklos/arc42-sample/$IMAGE_NAME:$IMAGE_TAG
